name: GPR
main: net.weasel.GPR.Radar
author: weasel5i2
version: 1.31
commands:
  gpr:
    description: GPR - Ground Penetrating Radar
    usage: "Usage: /scan [<depth>] - can be preset with /setscan"
    aliases: scan
  setscan:
    description: Sets the default scan depth
    usage: "Usage: /setscan <depth>"